server:
  port: 8081
  servlet:
    contextPath: /firstSpring
    encoding:
      charset: UTF-8
      enabled: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    password: admin
    url: jdbc:mysql://localhost:3306/bookshopbd2?user=root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    mandatory-file-encoding: UTF-8

paypal:
  client:
    id: ARNBABUvqAgPzdpB5net7G9_1-CpUlOvDeLPf59KEYmhV7mhxaE11fVtF8YxeJr2jMd8pKdub6s99pZg
    secret: EPJXYuTvDNPAfMoZwH80lbQTZrV6e9CaqdQMZzgoh9_egVlJJ7PVh9FnjcZt6ANOGzJj3XUWM4Rbc0gp
  mode: sandbox
